baseURL: https://example.com
title: Tom Mosher
languageCode: en-us
theme: hugo-theme-hello-friend-ng
PygmentsCodeFences: yes
PygmentsStyle: monokai
paginate: 10
rssLimit: 10
copyright: This work is licensed under a Creative Commons Attribution-NonCommercial
  4.0 International License.
archetypeDir: archetypes
contentDir: content
dataDir: data
layoutDir: layouts
publishDir: public
buildDrafts: no
buildFuture: no
buildExpired: no
canonifyURLs: yes
enableRobotsTXT: yes
enableGitInfo: no
enableEmoji: yes
enableMissingTranslationPlaceholders: no
disableRSS: no
disableSitemap: no
disable404: no
disableHugoGeneratorInject: no
permalinks:
  posts: /posts/:year/:month/:title/
author:
  name: Tom Mosher
blackfriday:
  hrefTargetBlank: yes
taxonomies:
  category: categories
  series: series
  tag: tags
params:
  customCSS: []
  customJS: []
  dateform: Jan 2, 2006
  dateformNum: '2006-01-02'
  dateformNumTime: 2006-01-02 15:04
  dateformShort: Jan 2
  description: Digital workings en brief
  disableReadOtherPosts: no
  enableGlobalLanguageMenu: no
  enableSharingButtons: no
  enableThemeToggle: no
  favicon:
    color:
      mask: '#1b1c1d'
      msapplication: '#1b1c1d'
      theme: '#1b1c1d'
  footer:
    author: yes
    bottomText:
      - Powered by <a href="http://gohugo.io">Hugo</a>
      - Made with &#10084; and many thanks to <a href="https://github.com/rhazdon">Djordje Atlialp</a>
    copyright: yes
    rss: no
    topText: []
    trademark: yes
  homeSubtitle: Open source creative and data scientist
  images: ''
  justifyContent: no
  keywords: ''
  logo:
    logoHomeLink: /
    logoMark: '>'
    logoText: $ cd /home/
  social:
    - name: email
      url: mailto:buscandoaverroes@icloud.com
    - name: github
      url: https://github.com/buscandoaverroes
languages:
  en:
    copyright: <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank"
      rel="noopener">CC BY-NC 4.0</a>
    subtitle: Hello Friend NG Theme
    weight: 1
  fr:
    copyright: <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank"
      rel="noopener">CC BY-NC 4.0</a>
    subtitle: Hello Friend NG Theme
    weight: 2
menu:
  main:
    - identifier: about
      name: About
      url: about/
    - identifier: posts
      name: Posts
      url: posts/
    - identifier: CV
      name: CV
      url: CV/
    - identifier: work
      name: Work
      url: work/
    - identifier: interests
      name: Interests
      url: interests/